import wikipediaapi # An API for wikipedia (surprisingly)
import re # Regex for funky string manipulation

wikiAPI = wikipediaapi.Wikipedia('en')

def getFromWiki(query):
    page = wikiAPI.page(query)
    pageData = page.summary
    pageData = pageData.split(".")[0]
    pageData = re.sub(r"\(|\)", "", re.sub(r"\(.*?\)", "", pageData)) # Obliterates bracket phrases
    pageData = re.sub(r" ,", ",", pageData) # Annihilates " ," generated by bracket phrases
    pageData = re.sub(r"  ", " ", pageData)
    pageData = re.sub(r" ,", ",", pageData)# Annihiltes thingy again (cause yeh)
    if pageData == "":
      pageData = None
    elif "may refer to" in pageData:
      pageData = None # We could change this to pick the top option and research
    # It's regex time lets go
    return pageData